### ISSUE TITLE
Spaced group vertical align & button line height

### ISSUE THREAD

**Issue by TheMightyGit** [dabapps/roe#103]
As I am a badass frontend developer, I have written the LESS for you. 😉 

```less
.spaced-group > * {
  vertical-align: top;
}

.button {
  line-height: 1.2em;
}
```

![screen shot 2017-08-09 at 15 09 35](https://user-images.githubusercontent.com/888751/29126964-a21bd288-7d17-11e7-948c-32032a6a4b45.png)
