### ISSUE TITLE
Allow re-triggering button pew

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/roe#176]
```less
button {
  &::after {
    content: '';
    transform: translate(-50%, -50%) scale(1, 1);
    opacity: 0;
    transition: ease-out 0.5s transform, ease-out 0.5s opacity;
  }

  &:active {
    &::after {
      transform: translate(-50%, -50%) scale(0, 0);
      opacity: 0.5;
      transition: none;
    }
  }
}
```
