### ISSUE TITLE
Set before and after in clearfix to width & height 0 (fixes Safari flexbox bug)

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/roe#233]
Also remove space from `content`?

```less
.clearfix {
  &::before,
  &::after {
    content: '';
    display: table;
    width: 0;
    height: 0;
  }
}
```
