### ISSUE TITLE
Ensure atomic classes override other things

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/roe#263]
E.g. `underline` does not correctly override link styling. Instead we should use:

```less
.underline {
  text-decoration: underline !important;
}
```
