### ISSUE TITLE
Fix table row headers regardless of whether they are actual headers & update class names

### ISSUE THREAD

**Issue by JakeSidSmith** [dabapps/roe#79]
```less
.fix-row-headers { // Needs updating
  tr {
    td:first-child,
    th:first-child {
      position: absolute;
      left: 0;
    }
  }
}
```
